sudo: required # Droit sudo
services:
  - docker # Copy d'une image docker

before_install:
  - docker build -t tcharlyson/docker-react -f Dockerfile.dev .

script:
  - docker run tcharlyson/docker-react npm run test -- --coverage